services:
  api:
    container_name: api.tamshyah.com
    image: tamshayh-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7549:7549"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
